services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./logs:/app/logs
    env_file:
      - .env
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Zurich